In [1]:
# Real Estate Forecasting - Preprocessing
# This notebook is responsible for preprocessing the data ingested in the previous step. 
# The data is cleaned and transformed to be ready for the next steps in the pipeline. 
# The cleaned data is saved as a pickle file for later use in the pipeline.

# Importing necessary libraries
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [2]:
# Importing the data from the CSV file
BASE_DIR = Path.cwd().parent.parent
data_path = BASE_DIR / "data" / "real_estate_data.csv"
df = pd.read_csv(data_path, encoding="utf-8")
df.sample(10)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,...,tras-pm2,Unnamed: 16,sector,v,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
9105,NaN,3,Comunidad,8,Castilla-La Mancha,98,CASTILLA-LA MANCHA,NaN,NaN,NaN,...,NaN,NaN,commercial,2019.0,1214.0,112419.0,"837,96",882.0,408797.0,"313,66"
4788,2023.0,3,Provincia,8,Castilla-La Mancha,16,Cuenca,1878.0,73770.0,"704,60",...,"535,21",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7551,NaN,1,Provincia,16,País Vasco,1,Araba / Álava,NaN,NaN,NaN,...,NaN,NaN,commercial,2014.0,227.0,116092.0,"1332,46",55.0,283417.0,"561,39"
1485,2012.0,1,Provincia,10,Comunitat Valenciana,3,Alicante / Alacant,20752.0,124777.0,"1361,72",...,"728,87",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10892,NaN,4,Provincia,5,Canarias,38,Santa Cruz de Tenerife,NaN,NaN,NaN,...,NaN,NaN,commercial,2025.0,1551.0,145238.0,"1573,52",100.0,653664.0,"846,40"
1697,2012.0,4,Provincia,9,Cataluña,17,Girona,6917.0,174455.0,"1876,90",...,"866,93",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8654,NaN,1,Comunidad,3,Principado de Asturias,98,PRINCIPADO DE ASTURIAS,NaN,NaN,NaN,...,NaN,NaN,commercial,2018.0,1018.0,97836.0,"832,82",132.0,323254.0,"410,47"
4155,2021.0,2,Comunidad,12,Galicia,98,GALICIA,17340.0,125343.0,"1319,73",...,"777,15",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5140,2024.0,4,Provincia,7,Castilla y León,37,Salamanca,3842.0,119005.0,"1225,51",...,"1115,07",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7677,NaN,3,Provincia,10,Comunitat Valenciana,3,Alicante / Alacant,NaN,NaN,NaN,...,NaN,NaN,commercial,2014.0,1486.0,127514.0,"982,43",200.0,362810.0,"394,05"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10944 entries, 0 to 10943
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ano          5472 non-null   float64
 1   trim         10944 non-null  int64
 2   geo          10944 non-null  object
 3   cod-ca       10944 non-null  int64
 4   ca           10944 non-null  object
 5   cod-prv      10944 non-null  int64
 6   prv          10944 non-null  object
 7   viv-num      5472 non-null   float64
 8   viv-imp      5472 non-null   float64
 9   viv-pm2      5472 non-null   object
 10  gar-num      5472 non-null   float64
 11  gar-imp      5472 non-null   float64
 12  gar-pm2      5472 non-null   object
 13  tras-num     5472 non-null   float64
 14  tras-imp     5472 non-null   float64
 15  tras-pm2     5472 non-null   object
 16  Unnamed: 16  0 non-null      float64
 17  sector       10944 non-null  object
 18  v            5472 non-null   float64
 19  loc-num      5472 non-null   float64
 20  loc-imp      5472 non-null   float64
 21  loc-pm2      5472 non-null   object
 22  nav-num      5472 non-null   float64
 23  nav-imp      5472 non-null   float64
 24  nav-pm2      5472 non-null   object
dtypes: float64(13), int64(3), object(9)
memory usage: 2.1+ MB

In [4]:
df.describe()

,ano,trim,cod-ca,cod-prv,viv-num,viv-imp,gar-num,gar-imp,tras-num,tras-imp,Unnamed: 16,v,loc-num,loc-imp,nav-num,nav-imp
count,5472.000000,10944.000000,10944.000000,10944.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,0.0,5472.000000,5472.000000,5472.000000,5472.000000,5.472000e+03
mean,2016.000000,2.500000,9.847222,46.375000,20672.421601,141602.431835,8286.295322,14606.387061,1617.883772,5320.863670,NaN,2016.000000,1933.686404,129787.319262,395.588450,3.898493e+05
std,5.477726,1.118085,11.759293,34.494102,62218.048108,52581.675253,24902.534933,4129.423777,4786.722582,1800.336443,NaN,5.477726,5828.073215,54529.866836,1181.991274,2.750290e+05
min,2007.000000,1.000000,1.000000,1.000000,238.000000,65777.000000,109.000000,5519.000000,14.000000,2112.000000,NaN,2007.000000,14.000000,37631.000000,0.000000,0.000000e+00
25%,2011.000000,1.750000,5.000000,18.750000,3179.750000,104678.750000,1244.500000,11882.500000,277.000000,4114.000000,NaN,2011.000000,300.750000,90287.750000,73.000000,2.056068e+05
50%,2016.000000,2.500000,8.000000,36.500000,7107.000000,129880.000000,2836.000000,13987.500000,630.500000,4935.500000,NaN,2016.000000,690.000000,119887.000000,138.000000,3.201810e+05
75%,2021.000000,3.250000,12.000000,98.000000,15159.000000,164446.000000,5853.500000,16586.500000,1346.000000,6081.000000,NaN,2021.000000,1424.000000,155057.000000,291.000000,4.935380e+05
max,2025.000000,4.000000,99.000000,99.000000,893310.000000,410322.000000,345635.000000,35488.000000,66575.000000,28340.000000,NaN,2025.000000,84133.000000,430318.000000,15718.000000,3.161442e+06

In [ ]:
# Dropping the unnamed column which is not needed for analysis
df.drop(columns=["Unnamed: 16"], inplace=True)