In [41]:
# Real Estate Forecasting - Ingestion
# This notebook is responsible for ingesting the data from the source and preparing it for the next steps in the pipeline.
# The data is ingested from a CSV file and stored in a pandas DataFrame. The DataFrame is then saved as a pickle file for later use in the pipeline.

# Importing necessary libraries
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [42]:
# Ingesting the data from the CSV files

BASE_DIR = Path.cwd().parent.parent

residential_path = BASE_DIR / "data" / "RP_ComprvResid_2007-4t2025.csv"
commercial_path = BASE_DIR / "data" / "RP_ComprvCom_2007-4t2025.csv"

df_residential = pd.read_csv(residential_path, sep=";", encoding="utf-8")
df_commercial = pd.read_csv(commercial_path, sep=";", encoding="utf-8")

In [43]:
df_residential.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,gar-num,gar-imp,gar-pm2,tras-num,tras-imp,tras-pm2,Unnamed: 16
3449,2018,4,Provincia,16,País Vasco,48,Bizkaia,10173,209093,"2416,41",5460,22050,"1478,82",1929,8636,"1269,96",NaN
3127,2017,4,Provincia,7,Castilla y León,47,Valladolid,4476,116655,"1115,63",1788,12650,"969,78",311,4752,"871,75",NaN
2835,2016,4,Provincia,7,Castilla y León,34,Palencia,1128,92818,"902,11",355,12390,"793,02",150,4068,"832,49",NaN
3810,2020,1,Comunidad,17,La Rioja,98,LA RIOJA,3468,103891,"1081,40",1760,10909,"802,27",272,6928,"698,68",NaN
4844,2023,4,Provincia,5,Canarias,38,Santa Cruz de Tenerife,12618,189650,"2288,20",3684,13108,"911,18",681,5456,"859,73",NaN

In [44]:
df_commercial.sample(5)

,v,trim,geo,cod-ca,ca,cod-prv,prv,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
2230,2014,3,Comunidad,19,Melilla,98,MELILLA,31,97480,"1154,44",11,218455,"646,20"
346,2008,1,Comunidad,14,Región de Murcia,98,REGIÓN DE MURCIA,2840,135566,"1252,51",487,260276,"427,20"
4772,2023,3,Provincia,5,Canarias,38,Santa Cruz de Tenerife,1173,128786,"1236,54",89,587580,"692,67"
5036,2024,2,Comunidad,18,Ceuta,98,CEUTA,29,111929,"1531,38",6,115000,"340,29"
5054,2024,3,Comunidad,3,Principado de Asturias,98,PRINCIPADO DE ASTURIAS,1059,86757,"903,45",147,401354,"408,83"

In [45]:
# Adding a new column to identify the sector of the data
df_residential['sector'] = 'residential'
df_commercial['sector'] = 'commercial'

# Concatenating the two DataFrames into one
df = pd.concat([df_residential, df_commercial], axis = 0, ignore_index=True)

In [46]:
df.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,...,tras-pm2,Unnamed: 16,sector,v,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
1456,2012.0,1,Comunidad,4,Illes Balears,98,ILLES BALEARS,7935.0,213881.0,"2003,90",...,"885,63",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6958,NaN,1,Provincia,10,Comunitat Valenciana,12,Castellón / Castelló,NaN,NaN,NaN,...,NaN,NaN,commercial,2012.0,553.0,116135.0,"981,05",135.0,345802.0,"724,47"
4431,2022.0,2,Comunidad,9,Cataluña,98,CATALUÑA,97375.0,218468.0,"2350,39",...,"1078,02",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6834,NaN,3,Comunidad,17,La Rioja,98,LA RIOJA,NaN,NaN,NaN,...,NaN,NaN,commercial,2011.0,890.0,97274.0,"1137,06",83.0,156239.0,"431,28"
8069,NaN,1,Provincia,1,Andalucía,18,Granada,NaN,NaN,NaN,...,NaN,NaN,commercial,2016.0,678.0,95133.0,"996,93",117.0,272807.0,"346,64"

In [47]:
# Saving the new DataFrame concatenated
df.to_csv(BASE_DIR / "data" / "real_estate_data.csv", index=False, encoding="utf-8")