In [10]:
# Real Estate Forecasting - Ingestion
# This notebook is responsible for ingesting the data from the source and preparing it for the next steps in the pipeline.
# The data is ingested from a CSV file and stored in a pandas DataFrame. The DataFrame is then saved as a pickle file for later use in the pipeline.

# Importing necessary libraries
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [32]:
# Ingesting the data from the CSV files

BASE_DIR = Path.cwd().parent.parent

residential_path = BASE_DIR / "data" / "RP_ComprvResid_2007-4t2025.csv"
commercial_path = BASE_DIR / "data" / "RP_ComprvCom_2007-4t2025.csv"

db_residential = pd.read_csv(residential_path, sep=";", encoding="utf-8")
db_commercial = pd.read_csv(commercial_path, sep=";", encoding="utf-8")

In [35]:
db_residential.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,gar-num,gar-imp,gar-pm2,tras-num,tras-imp,tras-pm2,Unnamed: 16
321,2008,1,Comunidad,8,Castilla-La Mancha,98,CASTILLA-LA MANCHA,37381,142756,"1329,05",10153,14360,"920,46",2979,4834,"841,02",NaN
4616,2023,1,Provincia,1,Andalucía,29,Málaga,39991,260039,"2375,94",13829,17059,"1013,18",3239,7893,"1080,33",NaN
3256,2018,2,Comunidad,4,Illes Balears,98,ILLES BALEARS,15782,251750,"2357,40",6201,16105,"1273,14",1020,6622,"1315,20",NaN
377,2008,2,Provincia,4,Illes Balears,7,Illes Balears,15499,220730,"2322,89",8012,16640,"1300,57",1396,7543,"1057,59",NaN
4394,2022,2,Provincia,1,Andalucía,4,Almería,14728,108990,"1141,27",5283,12062,"715,61",730,4626,"689,85",NaN

In [36]:
db_commercial.sample(5)

,v,trim,geo,cod-ca,ca,cod-prv,prv,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
4988,2024,2,Provincia,5,Canarias,38,Santa Cruz de Tenerife,1294,126579,"1319,43",74,569801,"746,90"
4425,2022,2,Comunidad,8,Castilla-La Mancha,98,CASTILLA-LA MANCHA,1289,81954,"694,93",695,682778,"340,93"
2042,2014,1,Provincia,7,Castilla y León,24,León,258,88454,"850,53",54,346091,"225,86"
4215,2021,3,Comunidad,9,Cataluña,98,CATALUÑA,7938,142570,"1352,67",1499,705095,"642,28"
5012,2024,2,Comunidad,10,Comunitat Valenciana,98,COMUNITAT VALENCIANA,8030,89178,"844,82",1258,418330,"474,21"

In [37]:
# Adding a new column to identify the sector of the data
db_residential['sector'] = 'residential'
db_commercial['sector'] = 'commercial'

# Concatenating the two DataFrames into one
db = pd.concat([db_residential, db_commercial], axis = 0, ignore_index=True)

In [39]:
db.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,...,tras-pm2,Unnamed: 16,sector,v,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
6904,NaN,4,Provincia,16,País Vasco,20,Gipuzkoa,NaN,NaN,NaN,...,NaN,NaN,commercial,2011.0,812.0,168511.0,"1976,43",144.0,419197.0,"879,20"
9370,NaN,3,Comunidad,2,Aragón,98,ARAGÓN,NaN,NaN,NaN,...,NaN,NaN,commercial,2020.0,1012.0,90229.0,"937,57",402.0,476326.0,"394,92"
1896,2013.0,3,Provincia,7,Castilla y León,5,Ávila,1351.0,99214.0,"965,17",...,"481,56",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6377,NaN,1,Provincia,9,Cataluña,17,Girona,NaN,NaN,NaN,...,NaN,NaN,commercial,2010.0,575.0,211347.0,"1801,05",84.0,470158.0,"651,72"
4443,2022.0,2,Comunidad,12,Galicia,98,GALICIA,20958.0,131090.0,"1405,94",...,"815,44",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# Saving the new DataFrame concatenated
db.to_csv(BASE_DIR / "data" / "real_estate_data.csv", index=False, encoding="utf-8")