In [ ]:
# Real Estate Forecasting - Ingestion
# This notebook is responsible for ingesting the data from the source and preparing it for the next steps in the pipeline.
# The data is ingested from a CSV file and stored in a pandas DataFrame. The DataFrame is then saved as a pickle file for later use in the pipeline.

# Importing necessary libraries
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Ingesting the data from the CSV files

BASE_DIR = Path.cwd().parent.parent

residential_path = BASE_DIR / "data" / "RP_ComprvResid_2007-4t2025.csv"
commercial_path = BASE_DIR / "data" / "RP_ComprvCom_2007-4t2025.csv"

df_residential = pd.read_csv(residential_path, sep=";", encoding="utf-8")
df_commercial = pd.read_csv(commercial_path, sep=";", encoding="utf-8")

In [3]:
set(df_residential.columns)
set(df_commercial.columns)

{'ca',
 'cod-ca',
 'cod-prv',
 'geo',
 'loc-imp',
 'loc-num',
 'loc-pm2',
 'nav-imp',
 'nav-num',
 'nav-pm2',
 'prv',
 'trim',
 'v'}

In [4]:
df_residential.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,gar-num,gar-imp,gar-pm2,tras-num,tras-imp,tras-pm2,Unnamed: 16
748,2009,3,Provincia,7,Castilla y León,37,Salamanca,2778,131629,"1305,86",2040,20924,"1452,24",230,7174,"759,15",NaN
1198,2011,1,Provincia,10,Comunitat Valenciana,12,Castellón / Castelló,7522,141114,"1610,27",3542,11146,"929,97",1085,3441,"702,02",NaN
3166,2017,4,Comunidad,19,Melilla,98,MELILLA,497,150305,"1563,18",203,18807,"1273,98",86,6068,"1130,70",NaN
2446,2015,2,Comunidad,19,Melilla,98,MELILLA,449,138905,"1463,43",181,15165,"1146,44",75,7474,"1291,14",NaN
1900,2013,3,Provincia,7,Castilla y León,37,Salamanca,2023,112553,"1161,12",1022,14416,"936,52",151,3556,"732,15",NaN

In [5]:
# Renaming the column 'v' to 'ano' in the residential DataFrame for better clarity and understanding of the data
df_commercial = df_commercial.rename(columns={"v": "ano"})

In [6]:
df_commercial.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
3131,2017,4,Provincia,8,Castilla-La Mancha,13,Ciudad Real,192,82297,"700,91",102,162337,"265,21"
5295,2025,2,Comunidad,9,Cataluña,98,CATALUÑA,11853,140673,"1357,15",1750,660771,"675,65"
3232,2018,1,Provincia,16,País Vasco,20,Gipuzkoa,1223,154308,"1612,33",203,525568,"710,65"
4839,2023,4,Provincia,3,Principado de Asturias,33,Asturias,1039,96826,"871,56",114,406047,"442,44"
4877,2023,4,Provincia,12,Galicia,27,Lugo,247,54181,"694,93",32,114755,"257,63"

In [7]:
# Adding a new column to identify the sector of the data
df_residential['sector'] = 'residential'
df_commercial['sector'] = 'commercial'

# Concatenating the two DataFrames into one
df = pd.concat([df_residential, df_commercial], axis = 0, ignore_index=True)

In [8]:
df.sample(5)

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,...,tras-imp,tras-pm2,Unnamed: 16,sector,loc-num,loc-imp,loc-pm2,nav-num,nav-imp,nav-pm2
10794,2025,2,Comunidad,17,La Rioja,98,LA RIOJA,NaN,NaN,NaN,...,NaN,NaN,NaN,commercial,678.0,78528.0,"874,07",141.0,217523.0,"372,34"
1609,2012,3,Provincia,7,Castilla y León,9,Burgos,2726.0,139314.0,"1403,54",...,6194.0,"965,00",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN
956,2010,2,Provincia,5,Canarias,38,Santa Cruz de Tenerife,8307.0,133391.0,"1603,57",...,4609.0,"844,26",NaN,residential,NaN,NaN,NaN,NaN,NaN,NaN
7766,2014,4,Comunidad,16,País Vasco,98,PAÍS VASCO,NaN,NaN,NaN,...,NaN,NaN,NaN,commercial,2113.0,156429.0,"1708,48",369.0,439768.0,"773,39"
10252,2023,3,Provincia,7,Castilla y León,37,Salamanca,NaN,NaN,NaN,...,NaN,NaN,NaN,commercial,353.0,102192.0,"898,35",88.0,279991.0,"386,73"

In [9]:
# Saving the new DataFrame concatenated
df.to_csv(BASE_DIR / "data" / "real_estate_data.csv", index=False, encoding="utf-8")